// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjXFPbRIMUiDxwm7lq6LcAMtk8eE8Tz8k',
    appId: '1:508326179650:web:d13d2a984c1ab261c80edb',
    messagingSenderId: '508326179650',
    projectId: 'ecommerce-bnpl',
    authDomain: 'ecommerce-bnpl.firebaseapp.com',
    storageBucket: 'ecommerce-bnpl.appspot.com',
    measurementId: 'G-8L5ZF9FHP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBPK2_w_6TP5gBCKqgK57ApaiTRKB123U',
    appId: '1:508326179650:android:c74e9634b7cb99afc80edb',
    messagingSenderId: '508326179650',
    projectId: 'ecommerce-bnpl',
    storageBucket: 'ecommerce-bnpl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJYGznu09tp1QuazBojBXHdWQtj3Fci4Q',
    appId: '1:508326179650:ios:226d24fa1628a32ec80edb',
    messagingSenderId: '508326179650',
    projectId: 'ecommerce-bnpl',
    storageBucket: 'ecommerce-bnpl.appspot.com',
    iosClientId: '508326179650-a55mccnio7vtefkruk7vu1rk145dbmjt.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceBnql',
  );
}
